### ISSUE TITLE
Utilize CSV.foreach method for optimized memory consumption

### ISSUE THREAD

**Issue by jwilsjustin** [ammoready/rsr_group#3]
You can read a CSV line-by-line rather than parsing it as a whole chunk. This will limit memory consumption dramatically. 

See here:
http://dalibornasevic.com/posts/68-processing-large-csv-files-with-ruby

**Comment by Oshuma** [comment]
:+1:

**Comment by jwilsjustin** [comment]
This is for Ruby 1.9.3, but should still apply: http://apidock.com/ruby/Net/FTP/gettextfile

We might be able to do all we need in a block we pass to the `#gettextfile` method:

> If a block is supplied, it is passed the retrieved data one line at a time.

**Comment by viacoffee** [comment]
Closed with #4
