### ISSUE TITLE
Catalog.all method is not returning the entire file.

### ISSUE THREAD

**Issue by jwilsjustin** [ammoready/rsr_group#9]
The `rsrinventory-new.txt` has 22,909 rows. The following code bellow is only processing the first 22,500 lines.

```ruby
@count = 0
RsrGroup::Catalog.all(750, credentials) do |chunk|
  chunk.each do |row|
    @count += 1
  end
end
@count #=> 22500
```

**Comment by jwilsjustin** [comment]
Looks like it's only iterating over the number of files that divides evenly into the `chunk_size` argument.

**Comment by viacoffee** [comment]
Pretty sure there was something in place to prevent this. I'll take a look at it.

**Comment by jwilsjustin** [comment]
I think it might have to do with the fact that there is no `yield` here: https://github.com/ammoready/rsr_group/blob/master/lib/rsr_group/catalog.rb#L46

**Comment by jwilsjustin** [comment]
Actually, maybe I'm wrong about that 🤔

**Comment by viacoffee** [comment]
It should be handled with `Chunker::is_complete?`

**Comment by jwilsjustin** [comment]
Whatever he cause I think the last "non-full" "Chunker" is getting missed.

**Comment by jwilsjustin** [comment]
Closing this in favor of #10.
